<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<link rel="stylesheet" href="style.css">';
echo '<title>About Us</title>';
echo '';
echo '</head>';
echo '<body>';
echo '<header class="header">';
echo '<div class="nav-items">';
echo '<nav>';
echo '<a href="#" class="logo">Mobile Planet</a>';
echo '<button class="hamburger" id="hamburger">';
echo ' <h3>Menu</h3>';
echo '</button>';
echo '<ul class="nav-ul" id="nav-ul">';
echo '<li><a href="Home.php" class="links">Home</a></li>';
echo '<li><a href="#" class="links">About</a></li>';
echo '<li><a href="Catalog.php" class="links">Services</a></li>';
echo '<li><a href="Enquire.php" class="links">Enquire</a></li>';
echo '<li><a href="index.php" class="links">Admin Login</a></li>';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '</header>';
echo '<main>';
echo '<div class="about-Us">';
echo '<h1>About Us </h1>';
echo '<p>Some text about who we are and what we do.</p>';
echo '<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere dignissimos aut provident magni mollitia, doloribus accusantium dolore? Officia, aliquid quidem. Atque aliquam itaque fugiat ad magni dolorum quas, nulla blanditiis!</p>';
echo '</div><hr>';
echo '<div class="Policy">';
echo '<h1>Policy </h1>';
echo '<p>Some text about our policy.</p>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam harum maxime, voluptatem molestias quasi maiores itaque mollitia sit laboriosam. Voluptatibus quisquam dolorem ab asperiores officiis magnam molestiae cumque alias! Explicabo!</p>';
echo '</div><hr>';
echo '<div class="Vision">';
echo '<h1>Vision</h1>';
echo '<p>Some text about the vision.</p>';
echo '<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deserunt repudiandae ipsa, iste sequi explicabo at eaque expedita porro minus obcaecati architecto, ducimus dolor fugiat ratione labore atque voluptatum possimus beatae..</p>';
echo '</div>';
echo '</main>';
echo '';
echo '';
echo '</div>';
echo '<footer class="footer">';
echo '<a href="#"><i class="fab fa-facebook"></i></a>';
echo '<a href="#"><i class="fab fa-twitter"></i></a>';
echo '<a href="#"><i class="fab fa-instagram"></i></a>';
echo '<div class="copy"> &copy; Shrapnel Technologies 2022 <hr><br></div>';
echo '</footer>';
echo '<script src="https://kit.fontawesome.com/c69fab0add.js" crossorigin="anonymous"></script>';
echo '';
echo '</body>';
echo '</html>';
?>