<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<link rel="stylesheet" href="style.css">';
echo '<title>Contact Us</title>';
echo '</head>';
echo '<body>';
echo '<header class="header">';
echo '<div class="nav-items">';
echo '<nav>';
echo '<a href="#" class="logo">Mobile Planet</a>';
echo '<button class="hamburger" id="hamburger">';
echo ' <h3>Menu</h3>';
echo '</button>';
echo '<ul class="nav-ul" id="nav-ul">';
echo '<li><a href="Home.php" class="links">Home</a></li>';
echo '<li><a href="About-US.php" class="links">About</a></li>';
echo '<li><a href="#" class="links">Catalog</a></li>';
echo '<li><a href="Enquire.php" class="links">Enquire</a></li>';
echo '<li><a href="Index.php" class="links">Admin Login</a></li>';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '</header>';
echo '<main>';
echo '<CEnter>';
echo '<h1>This is Our catalog</h1><hr>';
echo '</CEnter>';
echo '';
echo '';
echo '<div class="outer-card-container">';
echo '';
echo '<div id="card-main-container" >';
echo '<div class="product-image">';
echo '<img src="macbook pro.jpg" width="50%">';
echo '</div>';
echo '<div>';
echo '<h3 class="tag"><u>Macbook Pro</u> </h3>';
echo '<p class="product-tag" >Laptops</p>';
echo '</div>';
echo '<p>3rd Gen, Core i5 | No SSD, RAM 4GB DDR3, 500GB | 2.6 GHz RPM 5400 CACHE 3MB | WINDOW 10, 1366 x 768 pixels</p>';
echo '<div>';
echo '<center>';
echo '<h5 class="price-tag">$799.99</h5><hr>';
echo '</center>';
echo '</div>';
echo '</div>';
echo '';
echo '<div id="card-main-container" >';
echo '<div class="product-image">';
echo '<img src="ip13.jpg" width="50%">';
echo '</div>';
echo '<div>';
echo '<h3 class="tag">Sony VIAO E Series Laptop</h3>';
echo '<p class="product-tag">Cellphones</p>';
echo '</div>';
echo '<p>3rd Gen, Core i5 | No SSD, RAM 4GB DDR3, 500GB | 2.6 GHz RPM 5400 CACHE 3MB | WINDOW 10, 1366 x 768 pixels</p>';
echo '<div>';
echo '<center>';
echo '<h5 class="price-tag">$799.99</h5><hr>';
echo '</center>';
echo '</div>';
echo '</div>';
echo '';
echo '<div id="card-main-container" >';
echo '<div class="product-image">';
echo '<img src="applTv.jpg" width="50%">';
echo '</div>';
echo '<div>';
echo '<h3 class="tag">Apple TV</h3>';
echo '<p class="product-tag">Electronics</p>';
echo '<p >Laptops</p>';
echo '</div>';
echo '<p>3rd Gen, Core i5 | No SSD, RAM 4GB DDR3, 500GB |A8 chip with 64-bit architecture| WINDOW 10, 1366 x 768 pixels</p>';
echo '<div>';
echo '<center><br>';
echo '<h5 class="price-tag">$799.99</h5><hr>';
echo '</center>';
echo '</div>';
echo '</div><hr>';
echo '<div id="card-main-container" >';
echo '<div class="product-image">';
echo '<img src="applwatch.jpg" width="50%">';
echo '</div>';
echo '<div>';
echo '<h3 class="font-weight-bold">Sony VIAO E Series Laptop</h3>';
echo '';
echo '<p class="product-tag" >Electronics</p>';
echo '</div>';
echo '<p>3rd Gen, Core i5 | No SSD, RAM 4GB DDR3, 500GB | 2.6 GHz RPM 5400 CACHE 3MB | WINDOW 10, 1366 x 768 pixels</p>';
echo '<div>';
echo '<center>';
echo '<h5 class="price-tag">$799.99</h5><hr>';
echo '</center>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<div id="card-main-container" >';
echo '<div class="product-image">';
echo '<img src="Airtag.jpg" width="50%">';
echo '</div>';
echo '<div>';
echo '<h3 class="font-weight-bold">Apple Airtag</h3>';
echo '<p >Electronical </p>';
echo '</div>';
echo '<p>3rd Gen, Core i5 | No SSD, RAM 4GB DDR3, 500GB | 2.6 GHz RPM 5400 CACHE 3MB | WINDOW 10, 1366 x 768 pixels</p>';
echo '<div>';
echo '<center>';
echo '<h5 class="price-tag">$799.99</h5><hr>';
echo '</center>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</main>';
echo '';
echo '<footer class="footer">';
echo '<a href="#"><i class="fab fa-facebook"></i></a>';
echo '<a href="#"><i class="fab fa-twitter"></i></a>';
echo '<a href="#"><i class="fab fa-instagram"></i></a>';
echo '<div class="copy"> &copy; Shrapnel Technologies 2022 <hr><br></div>';
echo '</footer>';
echo '<script src="https://kit.fontawesome.com/c69fab0add.js" crossorigin="anonymous"></script>';
echo '<script src= "respnsive.js"></script>';
echo '';
echo '';
echo '</body>';
echo '</html>';
?>