<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<link rel="stylesheet" href="style.css">';
echo '';
echo '<title>Home</title>';
echo '</head>';
echo '<body>';
echo '<header class="header">';
echo '<div class="nav-items">';
echo '<nav>';
echo '<a href="#" class="logo">Mobile Planet</a>';
echo '<button class="hamburger" id="hamburger">';
echo ' <h3>Menu</h3>';
echo '</button>';
echo '<ul class="nav-ul" id="nav-ul">';
echo '<li><a href="#" class="links">Home</a></li>';
echo '<li><a href="About-Us.php" class="links">About</a></li>';
echo '<li><a href="Catalog.php" class="links">Catalog</a></li>';
echo '<li><a href="Enquire.php" class="links">Enquire</a></li>';
echo '<li><a href="index.php" class="links">Admin Login</a></li>';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '</header>';
echo '<main>';
echo '<div class="intro">';
echo '<h1>iMobile Planet</h1>';
echo '<p>Your Number one apple gadget supply.</p>';
echo '<button>Learn More</button>';
echo '</div>';
echo '<div class="achievements">';
echo '<div class="work">';
echo '<i class="fa-thin fa-mobile"></i>';
echo '<p class="work-heading">Devices</p>';
echo '<p class="work-text">A certified and official subsidiary of Apple .</p>';
echo '</div>';
echo '<div class="work">';
echo '<i class="fa-thin fa-headphones-simple"></i>';
echo '<p class="work-heading">Accessories</p>';
echo '<p class="work-text">Trusted supply for all apple gadget Accessories.</p>';
echo '</div>';
echo '<div class="work">';
echo '<i class="fa-thin fa-screwdriver-wrench"></i>';
echo '<p class="work-heading">Services</p>';
echo '<p class="work-text">Gadget repairing certificate.</p>';
echo '</div>';
echo '</div>';
echo '<div class="about-me">';
echo '<div class="about-me-text">';
echo '<h2>Brief</h2>';
echo '<p>We supply and fix apple gadgets. We also maintain </p>';
echo '</div>';
echo '<img src="iplanet.jpg" alt="apple">';
echo '</div>';
echo '</main>';
echo '';
echo '</div>';
echo '<footer class="footer">';
echo '<a href="#"><i class="fab fa-facebook"></i></a>';
echo '<a href="#"><i class="fab fa-twitter"></i></a>';
echo '<a href="#"><i class="fab fa-instagram"></i></a>';
echo '<div class="copy"> &copy; Shrapnel Technologies 2022 <hr><br></div>';
echo '</footer>';
echo '<script src="https://kit.fontawesome.com/c69fab0add.js" crossorigin="anonymous"></script>';
echo '<script src= "respnsive.js"></script>';
echo '';
echo '</body>';
echo '</html>';
?>